apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway  
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_SERVER_URL
              value: "movies-service:50051"
            - name: HTTP_PORT
              value: "8080"
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq-service:5672/